version: 2
jobs:
   build:
    working_directory: /splicing-pipeline
    docker:
      - image: docker:17.05.0-ce-git
    # heavily inspired from https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1 make
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/splicing-pipeline.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/splicing-pipeline.tar | true
      - run:
          name: Build application Docker image
          working_directory: /splicing-pipeline/pipeline/splicing
          command: |
            docker build --cache-from=splicing-pipeline -t splicing-pipeline .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/splicing-pipeline.tar splicing-pipeline
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/splicing-pipeline.tar
      - run:
          name: Run tests
          working_directory: /splicing-pipeline/pipeline/splicing
          command: |
            make unit_tests_docker -e IMAGE_NAME=splicing-pipeline
workflows:
   version: 2
   build-n-deploy:
     jobs:
       - build:
           filters:
             tags:
               only: /.*/
